In [7]:
import numpy as np

In [11]:
class Vector:
    def __init__(self, coordinates):
        try:
            if not coordinates:
                raise ValueError
            self.coordinates = tuple(coordinates)
            self.dimension = len(coordinates)
            
        except ValueError:
            raise ValueError('The coordinates must be nonempty')
            
        except TypeError:
            raise TypeError('The coordinates must be an interable.')
            
    def __str__(self):
        return f'Vector: {self.coordinates}'
    
    def __eq__(self, v):
        return self.coordinates == v.coordinates
    
    def plus(self, v):
        new_coordinates = [x + y for x,y in zip(self.coordinates, v.coordinates)]
        return Vector(new_coordinates)
    
    def minus(self, v):
        new_coordinates = [x - y for x,y in zip(self.coordinates, v.coordinates)]
        return Vector(new_coordinates)
    
    def times_scalar(self, c):
        new_coordinates = [c*x for x in self.coordinates]
        return Vector(new_coordinates)

In [2]:
my_vector = Vector([1,2,3])

In [3]:
my_vector

In [4]:
my_vector.coordinates

(1, 2, 3)

In [5]:
my_vector.dimension

3

In [6]:
print(my_vector)

Vector: (1, 2, 3)


In [8]:
np.array([8.218,-9.341]) + np.array([-1.129, 2.111])

array([ 7.089, -7.23 ])

In [9]:
np.array([7.119,8.215]) - np.array([-8.223, 0.878])

array([15.342,  7.337])

In [10]:
7.41 * np.array([1.671,-1.012,-0.318])

array([12.38211, -7.49892, -2.35638])